export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";
export const CART_INCREMENT_PRODUCT_QUANTITY = "CART_INCREMENT_PRODUCT_QUANTITY";
export const CART_DECREMENT_PRODUCT_QUANTITY = "CART_DECREMENT_PRODUCT_QUANTITY";

export const FAVORITE_ADD_PRODUCT = "FAVORITE_ADD_PRODUCT";
export const FAVORITE_REMOVE_PRODUCT= "FAVORITE_REMOVE_PRODUCT";

